name: proj_simp
description: "Simpsons Character Viewer"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0-53.0.dev <4.0.0'

dependencies:

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  http: ^1.1.0

  char_viewer_content:
    path: ../the_content

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/config.json
    - lib/place_holder.png
